version: 2.1
jobs:
  build-and-test:
    parallelism: 1
    macos:
      xcode: "14.3.1"
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: swift build -v | xcpretty
      - run: swift test -v | xcpretty

workflows:
  version: 2.1
  build-and-test:
    jobs:
      - build-and-test
